<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Turnos.Domain\Turnos.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Infrastructure\Auth\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Mapper\" />
    <Folder Include="Services\" />
    <Folder Include="Responses\" />
    <Folder Include="Requests\" />
  </ItemGroup>

</Project>
